### PR TITLE
Allow supplying data file handler.

### PR DESCRIPTION
**Pull request by zero725**
As consumers of the SDK we have a need to support custom reading and writing of the data files within Optimizely. This PR makes changes to allow for this customization by supporting the injection of an `OPTDatafileHandler` that can implement these custom behaviors.

There are three main areas of this PR:
* Allow for injecting a `OPTDatafileHandler` during the construction of the `OptimizelyClient`. If not supplied then the standard `DefaultDatafileHandler` is utilized. 
* Open the existing implementation of `DefaultDatafileHandler` so that it can be extended by consumers of the SDK and injected via `OptimizelyClient` construction.
* Open the existing implementation of `DataStoreFile` so that it can be easily extended to support custom reading and writing of `Data`, and utilized in extended versions of  `OPTDatafileHandler`/ `DefaultDatafileHandler`.

### CODE REVIEW

**Comment by jaeopt** [comment]
@zero725 Thanks for your contribution. We'll take a look at it. 
Can you sign our CLA if not done yet: https://github.com/optimizely/swift-sdk/blob/master/CONTRIBUTING.md

**Comment by jaeopt** [comment]
@zero725 Wondering what are the limitations in DefaultDatafileHandler you want to fix with the extension?
Do you need other file url for the storage?

**Comment by zero725** [comment]
Hello @jaeopt, one use case is to provide a handler which allows for local storage of data in a way that is not viewable/editable.

**Comment by ismailmustafa** [comment]
@jaeopt Is there anything we can do to get this reviewed or are there any changes you'd like to see made to this before it can be merged?

**Comment by jaeopt** [comment]
@ismailmustafa @zero725 The code changes look good. We're investigating impacts of its opening. We'll let you know if we need a help from your side.

**Comment by zero725** [comment]
Hi @jaeopt! How is the impact investigation coming along? Anything we can do to help?

**Review by jaeopt — COMMENTED** [review]
@zero725 The suggested changes look good and will be merged.
I pushed more required changes, renaming, and tests, etc.

**Review by jaeopt — APPROVED** [review]
LGTM

**Pull request merged**
