### PR TITLE
Correct minor typo in error message - 'experiement'

### PR DESCRIPTION
**Pull request by gemmakbarlow**
## Summary
- Noticed this printing to our console earlier today; typo now corrected.

## Test plan
- Confirming everything builds & passes on CI should be sufficient here

## Issues
- N / A

### CODE REVIEW

**Comment by jaeopt** [comment]
@gemmakbarlow Thanks for your contribution. If not done yet, can you sign our CLA?
https://github.com/optimizely/swift-sdk/blob/master/CONTRIBUTING.md

**Comment by gemmakbarlow** [comment]
> @gemmakbarlow Thanks for your contribution. If not done yet, can you sign our CLA? https://github.com/optimizely/swift-sdk/blob/master/CONTRIBUTING.md

Thanks for the flag @jaeopt; CLA now completed ✅

**Comment by gemmakbarlow** [comment]
> > @gemmakbarlow Thanks for your contribution. If not done yet, can you sign our CLA? https://github.com/optimizely/swift-sdk/blob/master/CONTRIBUTING.md
> 
> Thanks for the flag @jaeopt; CLA now completed ✅

I see I've got a few other things to tidy-up to match the guidelines; will do that shortly.

**Review by jaeopt — APPROVED** [review]
LGTM

**Pull request merged**
